USE SCHEMA SPINCO_SRC ;

CREATE TABLE DIM_ORDERS
(
ORDERKEY	NUMBER(38,0),
CUSTKEY		NUMBER(38,0),
ORDERSTATUS	VARCHAR(1),
TOTALPRICE	NUMBER(12,2),
ORDERDATE	DATE,
ORDERPRIORITY	VARCHAR(15),
CLERK		VARCHAR(15),
SHIPPRIORITY	NUMBER(38,0),
COMMENT		VARCHAR(79)
);
